### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-c6fty#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by PuddingNL** [comment]
![Schermafbeelding 2022-09-16 om 14 07 57](https://user-images.githubusercontent.com/1523612/190635587-946c09df-7de2-4918-b7d5-c4e11b941fd5.png)
